repos:
-   repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.271
    hooks:
      - id: ruff
-   repo: https://github.com/timothycrosley/isort
    rev: 5.13.0
    hooks:
    -   id: isort
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [src, -v, -i, --fail-under=30]
